// __example/box3/src/pages/CoffeeGuide.tsx
import React from 'react';
import CoffeeList from '../components/CoffeeList';
import HealthyTips from '../components/HealthyTips';

const CoffeeGuide = () => {
  return (
    <div>
      <h1 className="text-3xl font-bold text-gray-800 mb-8 text-center">咖啡营养指南</h1>
      <CoffeeList />
      <HealthyTips />
    </div>
  );
};

export default CoffeeGuide;

// __example/box3/src/views/CoffeeGuide.vue
<template>
  <div>
    <h1 class="text-3xl font-bold text-gray-800 mb-8 text-center">咖啡营养指南</h1>
    <CoffeeList />
    <HealthyTips />
  </div>
</template>

<script setup lang="ts">
import CoffeeList from '../components/CoffeeList.vue';
import HealthyTips from '../components/HealthyTips.vue';
</script>
